# Generated by Django 3.1.6 on 2021-02-23 07:31

from django.db import migrations
import enumchoicefield.fields
import outboxEDU.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=enumchoicefield.fields.EnumChoiceField(default=outboxEDU.authentication.models.Role(1), enum_class=outboxEDU.authentication.models.Role, max_length=9),
        ),
    ]
